spring:
  application:
    name: pharmacy-way  # 애플리케이션 이름 설정

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # ✅ 환경변수가 없으면 'local' 프로필 사용

---
# ✅ 공통 설정 (common profile)
spring:
  config:
    activate:
      on-profile: common  # 모든 환경에서 공통적으로 적용되는 설정

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}  # ✅ 환경변수에서 Kakao API 키 로드 (필수 설정)

---
# ✅ 로컬 환경 설정 (local profile)
spring:
  config:
    activate:
      on-profile: local  # 'local' 프로필이 활성화되었을 때만 적용

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB 드라이버
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation  # 로컬 DB 연결
    username: ${SPRING_DATASOURCE_USERNAME}  # 환경변수에서 로드
    password: ${SPRING_DATASOURCE_PASSWORD}  # 환경변수에서 로드

  jpa:
    hibernate:
      ddl-auto: update  # ✅ 개발 환경에서는 update, 운영 환경에서는 validate 또는 none 추천
    show-sql: true  # SQL 쿼리 로깅 (운영 환경에서는 OFF 권장)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect  # ✅ MariaDB용 Hibernate dialect
        format_sql: true  # SQL 쿼리를 보기 쉽게 포맷팅

  data:
    redis:
      host: localhost  # Redis 서버 주소
      port: 6379       # Redis 포트 번호

---
# ✅ 운영 환경 설정 (prod profile)
spring:
  config:
    activate:
      on-profile: prod  # 'prod' 프로필이 활성화되었을 때만 적용

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${SPRING_DATASOURCE_HOST:prod-db-host}:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # ✅ 운영 환경에서는 validate 또는 none 사용 (데이터 손실 방지)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false  # ✅ 운영 환경에서는 SQL 포맷팅 비활성화 추천

  data:
    redis:
      host: ${REDIS_HOST:prod-redis-host}
      port: 6379  # 운영 환경에 맞게 수정 가능

  # ✅ 추가적인 운영 환경 설정 가능 (예: 로깅, 캐시 설정 등)