spring:
  application:
    name: pharmacy-way

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # ✅ 실행 시 환경변수가 없으면 'local' 사용

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # 운영 환경을 고려해 create → update 변경
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect  #
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: prod

  # ✅ 운영 환경용 설정 추가 가능 (원하는 거 넣어라)
